School Project/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using NuGet.DependencyResolver;
using School_Project.Models;
using School_Project.Repositry;

namespace School_Project.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseRepository _courserepository;
        private readonly ITeacherRepository _teacherRepository;
        public CourseController(ICourseRepository courseRepository, ITeacherRepository teacherRepository)
        {
            _courserepository = courseRepository;
            _teacherRepository = teacherRepository;
        }
        [HttpGet]
        public ActionResult Index()
        {
            List<Course> stdlist = _courserepository.GetallCourses();

            return View(stdlist);
        }

        [HttpGet]
        public ViewResult Create()
        {
            List<Teacher> Teachherlist = _teacherRepository.GetAllTeachers();
            return View(Teachherlist);
        }


        [HttpPost]
        public ActionResult Create(Course course)
        {
            _courserepository.Create(course);
            List<Course> courseslist = _courserepository.GetallCourses();

            return View("Index", courseslist);
        }

        public ActionResult Delete(int id)
        {
            _courserepository.Delete(id);
            List<Course> courselist = _courserepository.GetallCourses();

            return View("Index", courselist);
        }
    }
}

School Project/Controllers/RoomController.cs
using Microsoft.AspNetCore.Mvc;
using School_Project.Models;
using School_Project.Repositry;

namespace School_Project.Controllers
{
    public class RoomController : Controller
    {
        private readonly IRoomRepository _roomRepository;

        public RoomController(IRoomRepository roomRepository)
        {
            _roomRepository = roomRepository;
        }
        [HttpGet]
        public ActionResult Index()
        {
            List<Room> roomlist = _roomRepository.GetAllRooms();

            return View(roomlist);
        }

        [HttpGet]
        public ViewResult Create()
        {

            return View();
        }


        [HttpPost]
        public ActionResult Create(Room room)
        {
            _roomRepository.Create(room);
            List<Room> roomlist = _roomRepository.GetAllRooms();

            return View("Index",roomlist);
        }

        [HttpDelete]
        public ActionResult Delete(int id)
        {
            _roomRepository.Delete(id);
            List<Room> roomlist = _roomRepository.GetAllRooms();

            return View("Index",roomlist);
        }


    }
}

School Project/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using School_Project.Models;
using School_Project.Repositry;
using School_Project.Views.Models;

namespace School_Project.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentRepositry _studentRepositry;
        private readonly ICourseRepository _courseRepository;
        private readonly IWebHostEnvironment _environment;

        public StudentController(IStudentRepositry studentReposi, ICourseRepository courseRepository, IWebHostEnvironment hostingEnvironment)
        {
            _studentRepositry = studentReposi;
            _courseRepository = courseRepository;
            _environment = hostingEnvironment;
        }
        // get List Of students
        [HttpGet]
        public ActionResult Index()
        {
            List<Student> stdlist = _studentRepositry.GetAllStudents();

            return View(stdlist);
        }
        // get the userinterface to add new student
        [HttpGet]
        public ViewResult Create()
        {

            return View();
        }

        // Submit to create a student
        [HttpPost]
        public ActionResult Create(Student Student, IFormFile StudentPhoto)
        {
            var wwRootPath = _environment.WebRootPath + "/StudentPictures/";
            Guid guid = Guid.NewGuid();
            string FullPath = System.IO.Path.Combine(wwRootPath, guid + StudentPhoto.FileName);

            using (var filestream = new FileStream(FullPath, FileMode.Create))
            {
                StudentPhoto.CopyTo(filestream);
            }

            Student.PhotoName = guid + StudentPhoto.FileName;
            _studentRepositry.Create(Student);
            List<Student> stdlist = _studentRepositry.GetAllStudents();
            return View("Index", stdlist);
        }


        public ActionResult Delete(int id)
        {
            _studentRepositry.Delete(id);
            List<Student> stdlist = _studentRepositry.GetAllStudents();
            return View("Index", stdlist);
        }

        [HttpGet]
        public ViewResult Register()
        {
            StudentViewModelcs data = new StudentViewModelcs();
            data.courses = _courseRepository.GetallCourses();
            data.Students = _studentRepositry.GetAllStudents();

            return View(data);
        }

        [HttpPost]
        public ActionResult Register(int studentid, int courseid)
        {
            _studentRepositry.Register(studentid, courseid);
            return RedirectToAction("Register");
        }
    }
}

School Project/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using School_Project.Context;
using School_Project.Models;
using School_Project.Repositry;

namespace School_Project.Controllers
{
    public class TeacherController : Controller
    {
        private readonly ITeacherRepository _teacherRepository;

        public TeacherController(ITeacherRepository teacherRepository)
        {
            _teacherRepository = teacherRepository;
        }
        // get List Of Teachers
        [HttpGet]
        public ActionResult Index()
        {
            List<Teacher> Teachherlist = _teacherRepository.GetAllTeachers();

            return View(Teachherlist);
        }
        // get the userinterface to add new Teacher
        [HttpGet]
        public ViewResult Create()
        {

            return View();
        }

        // Submit to create a Teacher
        [HttpPost]
        public ActionResult Create(Teacher teacher)
        {
            _teacherRepository.Create(teacher);
            List<Teacher> Teachherlist = _teacherRepository.GetAllTeachers();

            return View("Index", Teachherlist);
        }


        public ActionResult Delete(int id)
        {
            _teacherRepository.Delete(id);
            List<Teacher> Teachherlist = _teacherRepository.GetAllTeachers();

            return View("Index", Teachherlist);
        }
    }
}

School Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - School_Project</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/School_Project.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Index">Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Room" asp-action="index">Rooms</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Register">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div style="position: fixed; bottom: 0; left: 0; width: 100%; text-align: left; background-color: #f1f1f1; padding: 10px;">
            &copy; 2025 - School_Project -
            <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>